# Generated by Django 3.2.7 on 2022-02-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayvanlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hayvansahibi',
            name='owner',
        ),
        migrations.AddField(
            model_name='hayvansahibi',
            name='owner',
            field=models.ManyToManyField(to='hayvanlar.Hayvan'),
        ),
    ]
