# Generated by Django 3.2.7 on 2022-02-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayvanlar', '0008_alter_hayvansahibi_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hayvan',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
