# Generated by Django 3.2.7 on 2022-03-18 13:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('hayvanlar', '0009_alter_hayvan_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HayvanSahibi',
            new_name='AnimalOwners',
        ),
        migrations.RenameModel(
            old_name='Hayvan',
            new_name='Animals',
        ),
    ]
