# Generated by Django 2.0 on 2022-03-28 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hayvanlar', '0011_auto_20220320_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_animal', to='hayvanlar.AnimalOwners'),
        ),
    ]
