# Generated by Django 2.0 on 2022-03-29 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hayvanlar', '0012_auto_20220329_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hayvanlar.AnimalOwners'),
        ),
    ]
