# Generated by Django 2.0 on 2022-04-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayvanlar', '0013_auto_20220330_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalowners',
            name='address',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='animalowners',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='animalowners',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='animalowners',
            name='surname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='animals',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animals',
            name='genus',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='animals',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='animals',
            name='type',
            field=models.CharField(max_length=15),
        ),
    ]
